"""empty message

Revision ID: 957bd4d260ed
Revises: 65824aff47a4
Create Date: 2019-08-11 12:55:08.575183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '957bd4d260ed'
down_revision = '65824aff47a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sa.String(length=11), nullable=False))
    op.drop_column('user', 'telepthon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telepthon', mysql.VARCHAR(length=11), nullable=False))
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###
